package:
  name: cparty
  version: "1.0.0"

source:
  path: ..
  # git_url: https://github.com/HosnaJabbari/CParty.git
  # git_rev: (latest tag)

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - cmake >=3.1
  host:
    - libstdcxx-ng    # [linux]
    - libcxx          # [osx]
  run:
    - libstdcxx-ng    # [linux]
    - libcxx          # [osx]

about:
  home: https://github.com/HosnaJabbari/CParty
  license: "MIT"
  license_file: LICENSE
  summary: "CParty is an algorithm for computing the conditional partition function for density-2 RNA pseudoknots."
  description: |
    CParty is a computational tool designed for RNA secondary structure prediction, 
    specifically computing the conditional partition function for density-2 RNA pseudoknots. 
    It enables users to analyze RNA sequences, predict minimum free energy structures, 
    calculate ensemble energy, and generate optimal RNA folding structures, 
    including pseudoknot-free and pseudoknotted configurations. 

    The software is implemented in C++ and requires a C++11-compatible compiler with CMake. 
    It is compatible with Linux and macOS systems and provides a command-line interface 
    with various options for input and output customization.

    For installation, usage instructions, and additional details, visit:
    https://github.com/HosnaJabbari/CParty
  dev_url: https://github.com/HosnaJabbari/CParty


extra:
  recipe-maintainers:
    - PointlessUser

test:
  commands:
    - CParty --help